version: '3.7'

services:
    frontend:
        container_name: frontend
        build:
            context: .
        command: ['yarn', 'start']
        ports:
            - '3000:3000'
        volumes:
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on: 
            - backend
        env_file: .env
        stdin_open: true # docker run -i
        tty: true # docker run -t 
        
    backend:
        container_name: backend
        build:
            context: .
        command: ['yarn', 'start-api']
        ports:
            - '5000:5000'
        volumes:
             - '.:/usr/src/app/'
             - '/usr/src/app/node_modules'
        env_file:
            - ./api/.flaskenv 
            - .env

