version: '3.7'

services:
    frontend:
        build:
            context: .
        command: ['yarn', 'start']
        ports:
            - 3000:3000
        volumes:
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        stdin_open: true # docker run -i
        tty: true # docker run -t 
        depends_on: 
            - backend

    backend:
        build:
            context: .
        command: ['yarn', 'start-api']
        expose: 
            - 5000
        volumes:
            - './api:/usr/src/app/'
        env_file:
            - ./api/.flaskenv 
        