version: '3.7'

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        depends_on: 
            - backend
        env_file: .env
        stdin_open: true # docker run -i
        tty: true # docker run -t 
    
    proxy:
        container_name: proxy
        build:
            context: ./proxy
            dockerfile: Dockerfile.dev
        ports:
            - '80:80'
        depends_on: 
            - frontend
            - backend
        
    backend:
        container_name: backend
        build:
            context: ./api
        ports:
            - '5000:5000'
        volumes:
             - '.:/usr/src/app/'
        env_file:
            - ./api/.flaskenv 
            - .env

