version: '3.7'

services:
    frontend:
        build:
            context: .
        ports:
            - 3000:3000
        volumes:
            - '.:/app'
            - '.:/app/node_modules'
    
    backend:
        build:
            context: ./api
        ports:
            - 5000:5000
        volumes:
            - './api:/api'
        depends_on:
            - frontend
