export const dogList =  [
       'Border Collie', 'Border Terrier', 'Brittany', 'Cairn Terrier',
       'Welsh Springer Spaniel', 'English Cocker Spaniel',
       'Cocker Spaniel', 'Papillon', 'Australian Cattle Dog',
       'Shetland Sheepdog', 'Siberian Husky', 'Lhasa Apso',
       'Affenpinscher', 'Dachshund', 'Miniature Schnauzer', 'Chihuahua',
       'Australian Terrier', 'Whippet', 'English Springer Spaniel',
       'West Highland White Terrier', 'Bedlington Terrier', 'Poodle',
       'Bichon Frise', 'German Shorthaired Pointer', 'Pointer',
       'Tibetan Spaniel', 'Labrador Retriever', 'Maltese', 'Pomeranian',
       'Shih Tzu', 'Australian Shepherd', 'Yorkshire Terrier',
       'Irish Setter', 'Pharaoh Hound', 'Brussels Griffon',
       'Golden Retriever', 'Samoyed', 'Beagle',
       'Chesapeake Bay Retriever', 'Tibetan Terrier', 'Gordon Setter',
       'English Setter', 'Pug', 'Briard', 'Norfolk Terrier',
       'Flat-Coated Retriever', 'Boston Terrier', 'Doberman Pinscher',
       'English Toy Spaniel', 'Belgian Tervuren',
       'Cavalier King Charles Spaniel', 'Dalmatian', 'Basset Hound',
       'Basenji', 'Italian Greyhound', 'Staffordshire Bull Terrier',
       'Bouvier des Flandres', 'Pembroke Welsh Corgi', 'Clumber Spaniel',
       'Dandie Dinmont Terrier', 'Saluki', 'Giant Schnauzer', 'Greyhound',
       'Scottish Terrier', 'Rottweiler', 'Kerry Blue Terrier',
       'Afghan Hound', 'Newfoundland', 'German Shepherd', 'Pekingese',
       'Old English Sheepdog', 'Akita', 'Rhodesian Ridgeback',
       'French Bulldog', 'Borzoi', 'Bernese Mountain Dog', 'Bull Terrier',
       'Boxer', 'Alaskan Malamute', 'Chow Chow', 'Bloodhound',
       'Irish Wolfhound', 'Bullmastiff', 'Mastiff', 'Great Dane',
       'Saint Bernard', 'Bulldog', 'Airedale Terrier',
       'American English Coonhound', 'American Eskimo Dog',
       'American Foxhound', 'American Staffordshire Terrier',
       'American Water Spaniel', 'Anatolian Shepherd Dog',
       'Bearded Collie', 'Beauceron', 'Belgian Malinois',
       'Belgian Sheepdog', 'Black and Tan Coonhound',
       'Black Russian Terrier', 'Bluetick Coonhound', 'Boykin Spaniel',
       'Canaan Dog', 'Cane Corso', 'Cardigan Welsh Corgi',
       'Cesky Terrier', 'Chinese Crested', 'Chinese Shar Pei', 'Collie',
       'Curly Coated Retriever', 'English Foxhound',
       'Entlebucher Mountain Dog', 'Field Spaniel', 'Finnish Lapphund',
       'Finnish Spitz', 'German Pinscher', 'German Wirehaired Pointer',
       'Glen of Imaal Terrier', 'Great Pyrenees',
       'Greater Swiss Mountain Dog', 'Harrier', 'Havanese',
       'Ibizan Hound', 'Icelandic Sheepdog', 'Irish Red and White Setter',
       'Irish Terrier', 'Irish Water Spaniel', 'Japanese Chin',
       'Keeshond', 'Komondor', 'Kuvasz', 'Lakeland Terrier', 'Leonberger',
       'Looked - nothing', 'Löwchen', 'Manchester Terrier',
       'Miniature Bull Terrier', 'Miniature Pinscher',
       'Neapolitan Mastiff', 'Norwegian Buhund', 'Norwegian Elkhound',
       'Norwegian Lundehund', 'Norwich Terrier',
       'NOT POSSIBLE IF NO INTELLIGENCE DATA',
       'Nova Scotia Duck Tolling Retriever', 'Otterhound',
       'Parson Russell Terrier', 'Petit Basset Griffon Vendeen', 'Plott',
       'Polish Lowland Sheepdog', 'Portuguese Water Dog', 'Puli',
       'Pyrenean Shepherd', 'Redbone Coonhound', 'Schipperke',
       'Scottish Deerhound', 'Sealyham Terrier', 'Shiba Inu',
       'Silky Terrier', 'Skye Terrier', 'Smooth Fox Terrier',
       'Soft-Coated Wheaten Terrier', 'Spinone Italiano',
       'Standard Schnauzer', 'Sussex Spaniel', 'Swedish Vallhund',
       'Tibetan Mastiff', 'Toy Fox Terrier', 'Vizsla', 'Weimaraner',
       'Welsh Terrier', 'Wire Fox Terrier', 'Wirehaired Pointing Griffon',
       'Xoloitzcuintli'
    ];

export const numNeighborList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(elt => elt.toString());
